name: Automated Tweeting

on:
  schedule:
    # Runs every 96 minutes (1.6 hours)
    - cron: '0 */2 * * *'  # GitHub Actions minimum interval is 1 hour, so we'll run every 2 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  tweet:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tweet bot
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY_GITHUB }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET_GITHUB }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN_GITHUB }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET_GITHUB }}
        TOGETHER_API_KEY: ${{ secrets.TOGETHER_API_KEY_GITHUB }}
      run: python main.py
      
    - name: Commit and push if there are changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add tweet_counter.json tweet_history.json
        git commit -m "Update tweet history and counter" || exit 0
        git push
